apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-manifests
spec:
  workspaces:
  - name: source
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"
    - name: ING_HOST
      description: The Ingress Router HostName like petclinic-xxx-<namespace>.apps.<domain>.<location>.aroapp.io
      type: string      
  steps:
    - name: apply
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-

          echo -----------------------------------  
          echo workingDir 
          pwd
          echo -----------------------------------
          echo listing current directory
          ls -al 
          echo -----------------------------------

          echo Checking Manifests files in the k8s directory
          echo -----------------------------------
          cp $(inputs.params.manifest_dir) $(inputs.params.manifest_dir)/deploy

          export ING_HOST=$(inputs.params.ING_HOST)
          # ls -Rl $(inputs.params.manifest_dir) | grep ingress.yaml

          for i in `ls $(inputs.params.manifest_dir) | grep ingress.yaml`
          do
            if [ -d "$i" ]
            then
              l $(inputs.params.manifest_dir)/$i ;
            else
              echo $(inputs.params.manifest_dir)/$i
              envsubst < $(inputs.params.manifest_dir)/$i > $(inputs.params.manifest_dir)/deploy/$i
              cat $(inputs.params.manifest_dir)/deploy/$i
            fi
          done

          ls -al $(inputs.params.manifest_dir)/deploy
          echo -----------------------------------

          echo Applying manifests in $(inputs.params.manifest_dir) directory
          oc apply -f $(inputs.params.manifest_dir)/deploy
          echo -----------------------------------