apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-manifests
spec:
  workspaces:
  - name: source
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"
    - name: ING_HOST
      description: The Ingress Router HostName like petclinic-xxx-<namespace>.apps.<domain>.<location>.aroapp.io
      type: string      
  steps:
    - name: apply
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-

          echo -----------------------------------  
          echo workingDir 
          pwd
          echo -----------------------------------
          echo listing current directory
          ls -al
          echo creating deploy directory ...
          mkdir $(inputs.params.manifest_dir)/deploy/
          echo -----------------------------------

          echo Checking Manifests files in the k8s/deploy/ directory
          echo -----------------------------------
          cp $(inputs.params.manifest_dir)/*.yaml $(inputs.params.manifest_dir)/deploy/
          ls -al $(inputs.params.manifest_dir)/deploy/
          echo -----------------------------------

          export INGRESS_HOST=$(inputs.params.ING_HOST)
          echo INGRESS_HOST=$INGRESS_HOST
          # ls -Rl $(inputs.params.manifest_dir) | grep ingress.yaml

          for i in `ls $(inputs.params.manifest_dir) | grep ingress.yaml`
          do
            if [ -d "$i" ]
            then
              l $(inputs.params.manifest_dir)/$i ;
            else
              echo found Ingress $(inputs.params.manifest_dir)/$i
              # envsubst < $(inputs.params.manifest_dir)/$i > $(inputs.params.manifest_dir)/deploy/$i
              # which envsubst
              # envsubst --version
              # sed -i -e "s/ING_HOST/route-config/" spring-petclinic-visits-service/k8s/petclinic-visits-ingress.yaml
              # cat spring-petclinic-visits-service/k8s/petclinic-visits-ingress.yaml  | sed -e "s/ING_HOST/${ING_HOST}/g" > spring-petclinic-visits-service/k8s/deploy/petclinic-visits-ingress.yaml
              cat $(inputs.params.manifest_dir)/$i | sed -e "s/ING_HOST/${INGRESS_HOST}/g" > $(inputs.params.manifest_dir)/deploy/$i
              echo ING_HOST substituted
              
              cat $(inputs.params.manifest_dir)/deploy/$i
              echo \n
              echo -----------------------------------
            fi
          done

          echo -----------------------------------

          echo Applying manifests in $(inputs.params.manifest_dir)/deploy directory
          oc apply -f $(inputs.params.manifest_dir)/deploy
          echo -----------------------------------