apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-mvn-output
spec:
  workspaces:
  - name: shared-workspace
  steps:
    - name: init
      image: bash:latest # mcr.microsoft.com/azure-cli:latest
      # command: ["/usr/local/bin/bash", "-c"] # which bash ==> /usr/local/bin/bash
      workingDir: /workspace
      script: | 
        #!/usr/local/bin/bash
        echo -----------------------------------   
        pwd
        java -version
        ls -al /usr/lib/jvm/msopenjdk-11
        ls -al 

        echo Checking Maven jar files in target output directory

        ls -al "./spring-petclinic-admin-server"
        ls -al "./spring-petclinic-admin-server/target"

        ls -al "./petclinic-api-gateway"
        ls -al "./petclinic-api-gateway/target"

        ls -al "./petclinic-config-server"
        ls -al "./petclinic-config-server/target"

        ls -al "./petclinic-customers-service"
        ls -al "./petclinic-customers-service/target"

        ls -al "./petclinic-vets-service"
        ls -al "./petclinic-vets-service/target"

        ls -al "./petclinic-visits-service"
        ls -al "./petclinic-visits-service/target"

        echo -----------------------------------  
      # sleep 10
      # timeout: 5s