apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-mvn-output
spec:
  workspaces: # https://tekton.dev/vault/pipelines-v0.22.0/tasks/#specifying-workspaces
  - name: output
    mountPath: /workspace
  steps:
    - name: init
      image: bash:latest # mcr.microsoft.com/azure-cli:latest
      # command: ["/usr/local/bin/bash", "-c"] # which bash ==> /usr/local/bin/bash
      workingDir: /workspace/output
      script: | 
        #!/usr/local/bin/bash
        echo -----------------------------------   
        pwd
        echo listing current directory
        ls -al 

        echo listing workspaces.output.path
        ls -al $(workspaces.output.path)

        echo Checking Maven jar files in target output directory

        ls -al "./spring-petclinic-admin-server"
        ls -al "./spring-petclinic-admin-server/target"

        ls -al "./petclinic-api-gateway"
        ls -al "./petclinic-api-gateway/target"

        ls -al "./petclinic-config-server"
        ls -al "./petclinic-config-server/target"

        ls -al "./petclinic-customers-service"
        ls -al "./petclinic-customers-service/target"

        ls -al "./petclinic-vets-service"
        ls -al "./petclinic-vets-service/target"

        ls -al "./petclinic-visits-service"
        ls -al "./petclinic-visits-service/target"

        echo -----------------------------------  
      # sleep 10
      # timeout: 5s
      volumeMounts:
        - mountPath: /tmp
          name: tmp-vol
  volumes:
    - name: tmp-vol
      emptyDir: {}