apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-mvn-output
spec:
  workspaces: # https://tekton.dev/vault/pipelines-v0.22.0/tasks/#specifying-workspaces
  - name: output
    mountPath: /workspace
  results:
  - name: GIT_COMMIT_ID
    description: The Git Commit ID  
  steps:
    - name: init
      image: bash:latest # mcr.microsoft.com/azure-cli:latest
      workingDir: /workspace
      script: | 
        # command: ["/usr/local/bin/bash", "-c"] # which bash ==> /usr/local/bin/bash
        #!/usr/local/bin/bash
        echo -----------------------------------  
        echo workingDir 
        pwd
        echo -----------------------------------
        echo listing current directory
        ls -al 
        echo -----------------------------------
        echo listing workspaces.output.path
        ls -al $(workspaces.output.path)
        echo -----------------------------------

        echo Checking Maven jar files in the target directory

        echo -----------------------------------
        echo "spring-petclinic-admin-server"
        ls -al "spring-petclinic-admin-server"
        ls -al "spring-petclinic-admin-server/target"
        echo -----------------------------------

        echo -----------------------------------
        echo "spring-petclinic-api-gateway"
        ls -al "spring-petclinic-api-gateway"
        ls -al "spring-petclinic-api-gateway/target"
        echo -----------------------------------

        echo -----------------------------------
        echo "spring-petclinic-config-server"
        ls -al "spring-petclinic-config-server"
        ls -al "spring-petclinic-config-server/target"
        echo -----------------------------------

        echo -----------------------------------
        echo "spring-petclinic-customers-service"
        ls -al "spring-petclinic-customers-service"
        ls -al "spring-petclinic-customers-service/target"
        echo -----------------------------------

        echo -----------------------------------
        echo "spring-petclinic-vets-service"
        ls -al "spring-petclinic-vets-service"
        ls -al "spring-petclinic-vets-service/target"
        echo -----------------------------------

        echo -----------------------------------
        echo "spring-petclinic-visits-service"
        ls -al "spring-petclinic-visits-service"
        ls -al "spring-petclinic-visits-service/target"
        echo -----------------------------------

       
        echo Get git.commit.id property from spring-petclinic-customers-service/target/classes/git.properties
        echo and set it as result, so that it can be reused then to Tag the Image
        echo -----------------------------------
        cat spring-petclinic-customers-service/target/classes/git.properties |
        while IFS='=' read -r key value;
          do
            if [ "$key" = "git.commit.id" ]
              then
                echo "$key"="$value"
                echo "$value" | tee /tekton/results/GIT_COMMIT_ID
            fi
          done
        echo -----------------------------------

        echo -----------------------------------  
      # sleep 10
      # timeout: 5s
      volumeMounts:
        - mountPath: /tmp
          name: tmp-vol
  volumes:
    - name: tmp-vol
      emptyDir: {}