apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-tag
spec:
  params:
    - name: IMAGE
      description: Image name to check Tag and Digest
      type: string
  results:
  - name: IMAGE_TAG
    description: The image Tag # https://github.com/containers/buildah/blob/main/docs/buildah-images.1.md
  steps:
    - name: get-tag
      image: quay.io/buildah/stable:latest
      command: ['buildah', 'images', '--filter=reference=$(inputs.params.IMAGE)', '--format={{.Tag}}']
      volumeMounts:
      - name: varlibcontainers
        mountPath: /var/lib/containers
    - name: get-digest
      image: quay.io/buildah/stable:latest
      command: ['buildah', 'images', '--filter=reference=$(inputs.params.IMAGE)', '--format={{.Digest}}']
      volumeMounts:
      - name: varlibcontainers
        mountPath: /var/lib/containers
    - name: set-results
      image: quay.io/buildah/stable:latest
      script: buildah images --filter reference=$(inputs.params.IMAGE) --format={{.Tag}} | tee /tekton/results/IMAGE_TAG
      volumeMounts:
      - name: varlibcontainers
        mountPath: /var/lib/containers
  volumes:
  - name: varlibcontainers
    emptyDir: {}