apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-tag
spec:
  params:
    - name: IMAGE
      description: Iname to check Tag and Digest
      type: string
  steps:
    - name: get-tag
      image: quay.io/buildah/stable:v1.14.8
      script: | 
        #!/usr/local/bin/bash
        tag=`buildah images --filter reference=$(inputs.params.IMAGE) --format "{{.Tag}}"`
        echo Tag $tag

        digest=`buildah images --filter reference=$(inputs.params.IMAGE) --format "{{.Digest}}"`
        echo Digest $digest