apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-tag
spec:
  params:
    - name: IMAGE
      description: Iname to check Tag and Digest
      type: string
  results:
  - name: IMAGE_TAG
    description: The image Tag   
  steps:
    - name: get-tag
      image: quay.io/buildah/stable:latest
      command: ['buildah', 'images', '--filter reference=$(inputs.params.IMAGE)', '--format "{{.Tag}}'] 
    - name: get-digest
      image: quay.io/buildah/stable:latest
      command: ['buildah', 'images', '--filter reference=$(inputs.params.IMAGE)', '--format "{{.Digest}}']