apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  workspaces:
  - name: shared-workspace
  - name: maven-settings
  # - name: local-maven-repo
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  - name: IMAGE
    type: string
    description: image to be build from the code
  - name: subdirectory
    type: string
    description: Subdirectory inside the `output` Workspace to clone the repo into
  - name: DOCKERFILE
    type: string
    description: Path to the Dockerfile to build.
  - name: CONTEXT
    type: string
    description: Path to the directory to use as context.
  - name: FORMAT
    type: string
    description: The format of the built container, oci or docker
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: maven-build
    taskRef:
      name: maven
      kind: ClusterTask
    params:
    - name: GOALS # https://hub.tekton.dev/tekton/task/maven
      value:
        # - -DskipTests
        - clean
        - package
        #- Dmaven.repo.local=$(workspaces.local-maven-repo.path)
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: maven-settings
      workspace: maven-settings      
    #- name: maven-repo
    #  workspace: local-maven-repo
    runAfter:
    - fetch-repository
  - name: check-mvn
    taskRef:
      name: check-mvn-output
    workspaces:
    - name: output
      workspace: shared-workspace
    runAfter:
    - maven-build    
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.IMAGE)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE)
    - name: CONTEXT
      value: $(params.CONTEXT)           
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - check-mvn
  - name: apply-manifests
    taskRef:
      name: apply-manifests
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - check-mvn
  - name: update-deployment
    taskRef:
      name: update-deployment
    params:
    - name: deployment
      value: $(params.deployment-name)
    - name: IMAGE
      value: $(params.IMAGE)
    runAfter:
    - apply-manifests
