apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-deployment
spec:
  params:
    - name: deployment
      description: The name of the deployment to patch the image
      type: string
    - name: IMAGE
      description: Location of image to be patched with
      type: string
    - name: IMAGE_DIGEST
      description: the IMAGE_DIGEST result from build-image Task results output
      type: string
    - name: IMAGE_TAG
      description: the IMAGE Tag
      type: string        
  steps:
    - name: patch
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo IMAGE=$(inputs.params.IMAGE)
          echo IMAGE_DIGEST=$(inputs.params.IMAGE_DIGEST)
          echo IMAGE_TAG=$(inputs.params.IMAGE_TAG)
          oc patch deployment $(inputs.params.deployment) --patch='{"spec":{"template":{"spec":{
            "containers":[{
              "name": "$(inputs.params.deployment)",
              "image":"$(inputs.params.IMAGE):$(inputs.params.IMAGE_TAG)"
            }]
          }}}}'
