apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-petclinic-ui
spec:
  rules:
  - host: route-ui-petclinic.apps.gbbappinno.northeurope.aroapp.io
    http:
      paths:
      - backend:
          serviceName: ui-service
          servicePort: 80
        path: /
      - backend:
          serviceName: ui-service
          servicePort: 8081
        path: /manage/health
      - backend:
          serviceName: ui-service
          servicePort: 8081
        path: /manage/info