
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
---            
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/manage"
      exposure: # https://docs.spring.io/spring-boot/docs/2.6.3/reference/html/actuator.html#actuator.endpoints.exposing
        include: "health,info,env,mappings" # "*"
        exclude: "beans"    
  endpoint:
    health:
      enabled: true
      status:
        http-mapping:
          down: 503
          fatal: 503
          out-of-service: 503
      group:
        readiness:
          include: "readinessState"
        liveness:
          include: "livenessState"                      
    probes:
        enabled: true      
    info:
      enabled: true
    env:
      enabled: true
    mappings:
      enabled: true            
  server:
    port: 8081
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888