apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-petclinic-admin-server
spec:
  rules:
  - host: ING_HOST
    http:
      paths:
      - path: /admin-server
        pathType: "Prefix"
        backend:
          service: 
            name: admin-server
            port: 
              number: 9090
      - path: /admin/manage/health
        pathType: "Prefix"
        backend:
          service:
            name: admin-server
            port: 
              number: 8081
      - path: /admin/manage/info
        pathType: "Prefix"
        backend:
          service:
            name: admin-server
            port: 
              number: 8081