apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-petclinic-admin-server
spec:
  rules:
  - host: route-ui-petclinic.apps.gbbappinno.northeurope.aroapp.io
    http:
      paths:
      - backend:
          serviceName: admin-server
          servicePort: 9090
        path: /admin-server
        pathType: "Prefix"
      - backend:
          serviceName: admin-server
          servicePort: 8081
        path: /manage/health
        pathType: "Prefix"
      - backend:
          serviceName: admin-server
          servicePort: 8081
        path: /manage/info
        pathType: "Prefix"