apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-petclinic-admin-server
spec:
  rules:
  - host: route-ui-petclinic.apps.gbbappinno.northeurope.aroapp.io
    http:
      paths:
      - path: /admin-server
        pathType: "Prefix"
        backend:
          service: 
            name: admin-server
            port: 
              number: 9090
      - path: /manage/health
        pathType: "Prefix"
        backend:
            name: admin-server
            port: 
              number: 8081
      - path: /manage/info
        pathType: "Prefix"
        backend:
            name: admin-server
            port: 
              number: 8081