apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-petclinic-customers
spec:
  rules:
  - host: route-ui-petclinic.apps.gbbappinno.northeurope.aroapp.io
    http:
      paths:
      - backend:
          serviceName: customers-service
          servicePort: 80
        path: /customers-service
      - backend:
          serviceName: customers-service
          servicePort: 80
        path: /api/customer/
      - backend:
          serviceName: customers-service
          servicePort: 8081
        path: /manage/health
      - backend:
          serviceName: customers-service
          servicePort: 8081
        path: /manage/info