apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: visits-service
  name: route-visits
spec:
  port:
    targetPort: http-8080
  to:
    kind: Service
    name: visits-service
    weight: 100 